
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RICKY
 */
public class PercobaanDialog extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private int optionType;

    /**
     * Creates new form PercobaanDialog
     */
    public PercobaanDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbError = new javax.swing.JRadioButton();
        rbInfo = new javax.swing.JRadioButton();
        rbWarning = new javax.swing.JRadioButton();
        rbPlain = new javax.swing.JRadioButton();
        txtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setBackground(new java.awt.Color(51, 255, 255));
        btn1.setText("Show Message");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 255, 255));
        btn2.setText("Yes/No Confirm");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 255, 255));
        btn3.setText("Yes/No/Cancel Confirm");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 255, 255));
        btn4.setText("Input Dialog (TextField)");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 255, 255));
        btn5.setText("Input Dialog (ComboBox)");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jLabel1.setText("Message Type");

        rbError.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        rbError.setText("Error Message");

        rbInfo.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        rbInfo.setText("Information");
        rbInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInfoActionPerformed(evt);
            }
        });

        rbWarning.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        rbWarning.setText("Warning");

        rbPlain.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        rbPlain.setText("Plain");

        txtField.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPlain)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbInfo)
                            .addComponent(rbWarning)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(rbError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPlain)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbInfoActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbError.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInfo.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlain.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        JOptionPane.showConfirmDialog(null, "Silahkan pilih Yes atau No","Confirm Title",JOptionPane.YES_NO_OPTION, optionType);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbError.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInfo.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlain.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        JOptionPane.showMessageDialog(null, "Contoh Show Message","Title Message", optionType);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbError.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInfo.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlain.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        JOptionPane.showConfirmDialog(null, "Silahkan pilih Yes, No atau Cancel", "Confirm Title", JOptionPane.YES_NO_CANCEL_OPTION, optionType);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbError.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInfo.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlain.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;

        JOptionPane.showInputDialog(null, "Masukkan Nama Anda disini: ", " Input Dialog Title", optionType);
        txtField.setText(btn4.getText());
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:int optionType = 0;
        int optionType = 0;
        if(rbError.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInfo.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlain.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        String[] Options = {"Apel", "Mangga", "Nanas", "Jeruk"};
        JOptionPane.showInputDialog(null, "Pilih Buah Kesukaan Anda?", "Title Pilih Buah" , optionType, null, Options, "Apel");
    }//GEN-LAST:event_btn5ActionPerformed

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        // TODO add your handling code here:
        btn4.getText();
    }//GEN-LAST:event_txtFieldActionPerformed
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PercobaanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PercobaanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PercobaanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PercobaanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PercobaanDialog().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbError;
    private javax.swing.JRadioButton rbInfo;
    private javax.swing.JRadioButton rbPlain;
    private javax.swing.JRadioButton rbWarning;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables

    private void txtField(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
